apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-shoumya
  namespace: shoumya
  labels:
    type: shoumya
spec:
  storageClassName: mysql-shoumya
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-shoumya"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-shoumya
  namespace: shoumya
  labels:
    type: shoumya
spec:
  storageClassName: mysql-shoumya
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi