apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: shoumya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      serviceFor: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      app: pages
      serviceFor: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            # Instead of using value directly we could also use secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-pass
            - name: MYSQL_SERVICE_HOST
              value: pages-mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: pages
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /-entrypoint-initdb.d
              #mountPath: "/var/lib/mysql-shoumya"
      volumes:
        - name: mysql-storage
          emptyDir: {}
          #persistentVolumeClaim:
           # claimName: mysql-volume-claim-shoumya
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: shoumya
  labels:
    serviceFor: mysql
    app: pages
spec:
  ports:
    - port: 3306
  selector:
    app: pages
    serviceFor: mysql
  type: NodePort
